<?xml version="1.0" encoding="utf-8"?>
<ThermalLabel Version="6.0" Width="4" Height="2.5" GapLength="0" MarkLength="0" OffsetLength="0" UnitType="Inch" LabelsPerRow="1" LabelsHorizontalGapLength="0" IsContinuous="False">
  <Items>
    <RectangleShapeItem Name="" X="0.1823" Y="0.2604" DataField="" DataFieldFormatString="" CacheItemId="" Comments="" Tag="" Width="3.6354" Height="2" FillColor="Black" />
    <TextItem Name="" X="0.4948" Y="0.5312" DataField="" DataFieldFormatString="" CacheItemId="" Comments="" Tag="" Width="1.0312" Height="0.2813" Text="sameer" BorderColor="White" Font="NativePrinterFontA,10,Point,,,False,90,,CP850" ForeColor="White" />
  </Items>
</ThermalLabel>